UI/WebStore_MVC/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore_MVC.Services.Interfaces;
using WebStore_MVC.ViewModels;

namespace WebStore_MVC.Components
{
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData productData;

        public BreadCrumbsViewComponent(IProductData productData)
        {
            this.productData = productData;
        }

        public IViewComponentResult Invoke()
        {
            var model = new BreadCrumbsViewModel();

            if(int.TryParse(Request.Query["SectionId"], out var section_id))
            {
                model.Section = productData.GetSection(section_id);
                if (model.Section?.ParentId is { } parent_section_id)
                    model.Section.Parent = productData.GetSection(parent_section_id);
            }

            if(int.TryParse(Request.Query["BrandId"], out var brand_id))
            {
                model.Brand = productData.GetBrand(brand_id);
            }

            if(int.TryParse(ViewContext.RouteData.Values["id"]?.ToString(), out var product_id))
            {
                model.Product = productData.GetProductById(product_id)?.Name;
            }

            return View(model);
        }
    }
}

UI/WebStore_MVC/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebStore.Domain;
using WebStore_MVC.Infrastructure.Mapping;
using WebStore_MVC.Services.Interfaces;
using WebStore_MVC.ViewModels;

namespace WebStore_MVC.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _ProductData;
        private readonly IConfiguration configuration;

        private const string _PageSizeConfigName = "CatalogPageSize";

        public CatalogController(IProductData productData, IConfiguration configuration)
        {
            _ProductData = productData;
            this.configuration = configuration;
        }

        public IActionResult Index(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null)
        {
            var page_size = PageSize ?? configuration.GetValue(_PageSizeConfigName, 6);


            var filter = new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Page = Page,
                PageSize = page_size,
            };

            var (products, total_count) = _ProductData.GetProducts(filter);

            return View(new CatalogViewModel
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Products = products
                .OrderBy(p => p.Order)
                .ToView(),
                PageViewModel = new PageViewModel
                {
                    Page = Page,
                    PageSize = page_size,
                    TotalItems = total_count,
                },
            }); ;
        }


        public IActionResult ProductDetails(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null) return NotFound();

            return View(product.ToView());
        }

        public IActionResult GetFeaturedItems(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null) =>
            PartialView("Partial/_FeaturedItems", GetProducts(BrandId, SectionId, Page, PageSize));

        private IEnumerable<ProductViewModel> GetProducts(int? BrandId, int? SectionId, int Page, int? PageSize) =>

             _ProductData.GetProducts(
                new ProductFilter
                {
                    BrandId = BrandId,
                    SectionId = SectionId,
                    Page = Page,
                    PageSize = PageSize ?? configuration.GetValue(_PageSizeConfigName, 6)
                }).Products.OrderBy(p => p.Order).ToView();
    }

}

UI/WebStore_MVC/Views/Catalog/Index.cshtml
@model WebStore_MVC.ViewModels.CatalogViewModel

@{ ViewBag.Title = "Product Catalog"; }

<section id="advertisement">
    <div class="container">
        <img src="~/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        @await Component.InvokeAsync("BreadCrumbs")
        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSlideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div id="catalog-items-container">
                    <partial name="Partial/_FeaturedItems" model="Model.Products" />
                </div>

                <paging page-model="Model.PageViewModel"
                        page-action="Index"
                        page-url-SectionId="@Model.SectionId"
                        page-url-BrandId="@Model.BrandId"
                        page-url-PageSize="@Context.Request.Query["PageSize"]">

                </paging>
            </div>
        </div>
    </div>
</section>

@section Scripts{

    <script src="~/js/Catalog//CatalogLogic.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>


    <script>
    $(function(){
        Catalog.init({
            getViewLink: "@Url.Action("GetFeaturedItems", "Catalog")"
        });
    })
    </script>
}