UI/WebStore_MVC/Controllers/AjaxTestController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebStore_MVC.ViewModels;

namespace WebStore_MVC.Controllers
{
    public class AjaxTestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetJSON(int? id, string msg, int Delay = 2000)
        {
            await Task.Delay(Delay);

            return Json(new
            {
                Message = $"Response(id:{id ?? 1}): {msg ?? "<null>"}",
                ServerTime = DateTime.Now
            });
        }

        public async Task<IActionResult> GetHTML(int? id, string msg, int Delay = 2000)
        {
            await Task.Delay(Delay);

            return PartialView("Partial/_DataView", new AjaxTestDataViewModel
            {
                Id = id ?? 1,
                Message = msg,
            });
        }

        public IActionResult SignalRTest() => View();

    }
}  

UI/WebStore_MVC/Views/AjaxTest/Index.cshtml
@{
    ViewData["Title"] = "Unobtrusive AJAX testing";
}

<div class="container">
    <h3>@ViewData["Title"]</h3>
    <hr/>

    <div class="row">
        <div class="col-md-4">
            <h4>Server-Side Rendering</h4>

            <a class="btn btn-default"
               data-ajax="true"
               data-ajax-url="@Url.Action("GetHTML", "AjaxTest", new { id = 42, msg = "MessageFromView_serverside", Delay = "500" })"
               data-ajax-loading="#spinner-server"
               data-ajax-update="#panel-server">Loading</a>

            <span id="spinner-server" style="display:none">
                <i class="fa fa-spinner fa-spin"></i>
            </span>

            <div id="panel-server"></div>
        </div>
        <div class="col-md-4">
            <h4>Client-Side Rendering</h4>
            <a class="btn btn-default"
               data-ajax="true"
               data-ajax-url="@Url.Action("GetJSON", "AjaxTest", new { id = 14, msg = "MessageFromView_clientside", Delay = "500" })"
               data-ajax-loading="#spinner-client"
               data-ajax-success="OnJSONLoaded">Loading</a>

            <span id="spinner-client" style="display:none">
                <i class="fa fa-spinner fa-spin"></i>
            </span>

            <div id="panel-client"></div>
             
        </div>
        <div class="col-md-4">
            <h4>Manual Forming</h4>

            <a id="load-data-button" class="btn btn-default">Loading</a>

            <div id="panel-js"></div>

        </div>
    </div>
</div>

@section Scripts{
                <script>
                    OnJSONLoaded = data => {
                        const panel = $("#panel-client");
                        panel.empty();
                        panel.append("msg " + data.message);
                        panel.append("<br/>");
                        panel.append("Server time: " + data.serverTime);
                    }

                    $("#load-data-button").click(e => {
                        e.preventDefault();

                        console.log("Starting AJAX-request to server");
                        $.get("@Url.Action("GetJSON", "AjaxTest")", { id: 123, msg: "fromManualPanel", Delay: "100" })
                            .done(data => {
                                console.log("Response from server");

                                const panel = $("#panel-js");
                                panel.empty();
                                panel.append("msg: " + data.message);
                                panel.append("<br/>");
                                panel.append("time: " + data.serverTime);
                            });

                    });


                </script>
            }

UI/WebStore_MVC/Views/AjaxTest/SignalRTest.cshtml
@{
    ViewData["Title"] = "Chat with SignalR";

}

<div class="container">
    <h4>Example of a chat</h4>

    <div>
        <div id="input-form">
            <input type="text" id="message"/>
            <input type="button" id="send-message" class="btn btn-default" value="Send" />
        </div>
        <ul id="information-block">

        </ul>
    </div>
</div>


@section Scripts
{
<script src="~/lib/aspnet-signalr/signalr.min.js"></script>
<script>
    const hub_url = "/chat";
    const connection = new signalR.HubConnectionBuilder().withUrl(hub_url).build();

    connection.on("MessageFromClient", data => $("#information-block").prepend($("<li></li>").html(data)));

    $("#send-message").click(e => connection.invoke("SendMessage", $("#message").val()));

    connection.start();
</script>

}